spring:
  config:
    activate:
      on-profile: local, test
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 50ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

---
spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: redis-master
    port: 6379
    database: 0

---
spring:
  config:
    activate:
      on-profile: qa
  redis:
    host: redis-master
    port: 6379
    database: 0

---
spring:
  config:
    activate:
      on-profile: prd
  redis:
    host: redis-master
    port: 6379
    database: 0