spring:
  config:
    activate:
      on-profile: local, test

datasource:
  redis:
    database: 0
    master:
      host: localhost
      port: 6379
    replicas:
      - host: localhost
        port: 6380

---
spring:
  config:
    activate:
      on-profile: dev

datasource:
  redis:
    database: 0
    master:
      host: redis-master
      port: 6379
    replicas:
      - host: redis-replica-1
        port: 6379

---
spring:
  config:
    activate:
      on-profile: qa

datasource:
  redis:
    database: 0
    master:
      host: redis-master
      port: 6379
    replicas:
      - host: redis-replica-1
        port: 6379

---
spring:
  config:
    activate:
      on-profile: prd

datasource:
  redis:
    database: 0
    master:
      host: redis-master
      port: 6379
    replicas:
      - host: redis-replica-1
        port: 6379